#!/usr/bin/env bash

WELLKNOWN=/letsencrypt
BASEDIR=/letsencrypt
CONTACT_EMAIL=$EMAIL
KEY_ALGO=${ALGORITHM:-secp384r1}

if [ -z ${STAGING+-} ]; then
  CA="https://acme-v02.api.letsencrypt.org/directory"
else
  CA="https://acme-staging-v02.api.letsencrypt.org/directory"
fi

